### ISSUE TITLE
Actually not an issue

### ISSUE THREAD

**Issue by zhivko** [ksksue/Android-USB-Serial-Monitor-Lite#2]
Hi!

I tryied to communicate with bus pirate from mk808 android device, but couldn't communicate to "bus pirate".

I used following code:
        // Get UsbManager from Android.
        UsbManager manager = (UsbManager) getSystemService(Context.USB_SERVICE);

```
    // Find the first available driver.
    UsbSerialDriver driver = UsbSerialProber.acquire(manager);

    if (driver != null) {
        try {
            driver.open();
            driver.setParameters(115200, UsbSerialDriver.DATABITS_8, UsbSerialDriver.STOPBITS_1,  UsbSerialDriver.PARITY_NONE);
            byte buffer[] = new byte[16];
            driver.write(("m" + "\r").getBytes(), 1000);
            int numBytesRead = driver.read(buffer, 1000);
            Log.d(this.getClass().getSimpleName(), "Read " + numBytesRead + " bytes: " + new String(buffer).toString());
        } catch (IOException e) {
            Log.d(this.getClass().getSimpleName(), e.getMessage());
        } finally {
            try {
                driver.close();
            } catch (IOException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
    }
```

From log I get strange characters back ( I am expecting to get something like bus pirate returns) - see below:
02-25 02:34:37.828: D/MainActivity(4888): device: /dev/bus/usb/001/007 Product id:24577 vendor id:1027
02-25 02:34:38.138: D/dalvikvm(4888): threadid=1: still suspended after undo (sc=1 dc=1)
02-25 02:34:41.708: D/FtdiSerialDriver(4888): claimInterface 0 SUCCESS
02-25 02:34:45.098: D/FtdiSerialDriver(4888): Wrote amtWritten=3 attempted=3
02-25 02:34:52.048: D/MainActivity(4888): Read 3 bytes: `??????????????????????????????

Actually I read something from bus pirate but it's not what I expected. I see from code of
AndroidUSBSerialMonitorLite.java
That you initialized the usb for ftdi FT232RL somehow different.
Is there some simple code (like I tried it above) to send something to bus pirate?

Thank you very much for any suggestion or code maybe.

**Comment by ksksue** [comment]
change

```
new String(buffer).toString()
```

to

```
byte[] rbuf = new byte[256];
char[] rchar = new char[256];
for(i=0; i<numBytesRead; i++) {
    rchar[i] = (char)rbuf[i];
}
String str = String.copyValueOf(rchar,0,numBytesRead);
```
