### ISSUE TITLE
CDC-ACM driver not supported?

### ISSUE THREAD

**Issue by jousterde1** [ksksue/Android-USB-Serial-Monitor-Lite#5]
My old CDC-ACM adapter works with USB Serial Monitor Lite app from google play but crashes this project...  Can you please update it to support the CDC-ACM protocol just like you did in your app?
Thank you for sharing!

**Comment by ksksue** [comment]
Please report Logcat's error code

**Comment by jousterde1** [comment]
Turned out I had the old version of FTDriver lib. Re-downloaded everything, compiled and did a test again with the new version - it now works with my ACM adapter.  Thanks for your response and again for sharing :)
